name: Tests
on: [push, pull_request]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.2, 8.3]
        composer-flags: [null, --prefer-lowest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.0.0
          
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          
      - name: Update Composer dependencies
        run: composer update ${{ matrix.composer-flags }} --no-interaction --no-progress --prefer-dist --ansi
        
      - name: Install npm dependencies
        run: npm install
      
        
      - name: Run PHPUnit tests
        run: |
        php artisan key:generate
        ./vendor/bin/phpunit --color=always
